# Generated by Django 4.1.7 on 2023-04-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
