# Generated by Django 4.1.7 on 2023-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testone',
            name='age',
            field=models.DateField(null=True),
        ),
    ]
