# Generated by Django 4.1.7 on 2023-03-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_test', '0002_testone_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testone',
            old_name='full_name',
            new_name='name',
        ),
    ]
