# Generated by Django 4.1.7 on 2023-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppo', '0002_rename_oppomodels_oppomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oppomodel',
            name='screen',
        ),
        migrations.AddField(
            model_name='oppomodel',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='oppomodel',
            name='screen_size',
            field=models.CharField(help_text='Please Enter size in inches.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oppomodel',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oppomodel',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Mobile Model'),
        ),
    ]
