# Generated by Django 4.1.7 on 2023-03-31 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oppo', '0003_remove_oppomodel_screen_oppomodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppomodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
