# Generated by Django 4.1.7 on 2023-03-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_samplemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='phone_number',
            field=models.CharField(help_text='Please Enter 11 Digits Phone Number', max_length=11, null=True),
        ),
    ]
