# Generated by Django 4.1.7 on 2023-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('Price', models.BigIntegerField(help_text='Price in Dollars $')),
                ('hard_drive_size', models.CharField(max_length=50)),
                ('screen_size', models.SmallIntegerField(help_text='Size in inches')),
                ('warrenty', models.CharField(choices=[('6M', '6_Month'), ('12M', '12_Month'), ('18M', '18_Month')], max_length=50)),
            ],
        ),
    ]
