# Generated by Django 4.1.7 on 2023-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('F', 'Faisalabad'), ('I', 'Islamabad'), ('L', 'London')], max_length=50)),
                ('contact', models.CharField(help_text='Please Enter 12 digits Contact Number', max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('short_bio', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
